@startuml



actor Client as Client
Client -> Controller: request
Controller -> Service: request
Service -> Cache : request
Cache --> Service : response if cache exists
Service --> Controller : response
Controller --> Client: response
Service -> Repository : request
database Database
Repository -> Database : request
Database -> Repository : response
Repository --> Service : response
Service --> Cache : cache response
Service --> Controller : response
Controller --> Client : response
@enduml
